apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metadata-ui-deployment.yaml
- metadata-ui-role.yaml
- metadata-ui-rolebinding.yaml
- metadata-ui-sa.yaml
- metadata-ui-service.yaml