apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: metadata-ui
  name: metadata-ui
spec:
  selector:
    matchLabels:
      app: metadata-ui
  template:
    metadata:
      labels:
        app: metadata-ui
    spec:
      containers:
      # TODO(rjbauer): Change this to something like gcr.io/metadata/frontend:0.0.1
      - image: gcr.io/rjbauer-ml-pipelines/metadata/frontend:0.0.1
        imagePullPolicy: IfNotPresent
        name: metadata-ui
        ports:
        - containerPort: 4000
      serviceAccountName: metadata-ui